---
- name: Q12 - Playbook for updating hosts entries on dev servers
  hosts: all
  gather_facts: true
  tasks:
    - name: Updating /etc/hosts using template
      ansible.builtin.template:
        src: host.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname in groups['dev']
