---
- name: Q7 - Playbook to configure issue file
  hosts: all
  tasks:
    - name: Update /etc/issue File on remote hosts
      ansible.builtin.copy:
        content: |
          {% if 'dev' in group_names %}
          Development
          {% elif 'test' in group_names %}
          Test
          {% elif 'prod' in group_names %}
          Production
          {% endif %}
        dest: /etc/issue
        mode: '0644'
      failed_when: false
        
