---
- name: Playbook 1 - Installing Packages
  hosts: dev,test,prod
  tasks:
    - name: Installing Packages
      ansible.builtin.dnf:
        name:
           - php
           - mariadb
        state: present

- name: Playbook 2 - Installing Dev Tools and Updating All on Dev Servers
  hosts: dev
  tasks:
    - name: Installing RPM Development Tools Packages
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present 
    
    - name: Updating Packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

