---
- name: Playbook1 - Configuring web-content
  hosts: dev
  gather_facts: true
  tasks:
    - name: Installing Packages
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: present

    - name: Creating webdev group
      ansible.builtin.group:
        name: webdev
        state: present

    - name: Creating /webdev directory
      ansible.builtin.file:
        name: /webdev
        state: directory
        group: webdev
        mode: '2775'
        setype: httpd_sys_content_t

    - name: Creating index.html file
      ansible.builtin.copy:
        content: Development
        dest: /webdev/index.html
        mode: '0644'
        setype: httpd_sys_content_t

    - name: Creating symbolic link for /webdev
      ansible.builtin.file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link

    - name: Starting Services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Allowing http service over firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

- name: Playbook2 - Testing web-content
  hosts: node2.lab.example.com
  tasks:
    - name: Accessing webcontent 
      ansible.builtin.uri:
        url: http://node1.lab.example.com/webdev
        return_content: true
        status_code: 200
      register: webcontent

    - name: Display webcontent
      ansible.builtin.debug:
        #var: webcontent.content
        msg: "{{ webcontent.content }}"
