---
- name: Q6 - Playbook to generate hwreport
  hosts: all
  gather_facts: true
  tasks:
    - name: Task 1 - Download the hwreport template
      ansible.builtin.get_url:
        url: http://10.10.1.200/materials/emptyhw.report
        dest: /root/hwreport.txt
        mode: '0644'

    - name: Task 2 - Updating hwreport on hosts
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: "{{ item.key }}"
        replace: "{{ item.value }}"
      loop:
        - key: inventory hostname
          value: "{{ ansible_facts['fqdn'] }}"
        - key: memory in MB
          value: "{{ ansible_facts['memtotal_mb'] | default ('NONE') }} MB"
        - key: BIOS_version
          value: "{{ ansible_facts['bios_version'] | default ('NONE') }}"
        - key: disk_sda_size
          value: "{{ ansible_facts['devices']['vda']['size'] | default ('NONE') }}"
        - key: disk_sdb_size
          value: "{{ ansible_facts['devices']['vdb']['size'] | default ('NONE') }}"
