---
- name: Configuring Yum Repository
  hosts: all
  tasks:
    - name: Importing GPG key
      ansible.builtin.rpm_key:
        key: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
        state: present

    - name: Configuring Base Repo
      ansible.builtin.yum_repository:
        file: ex294_repo
        name: EX294_BASE
        description: EX294 base software
        baseurl: http://10.10.1.200/alma10/BaseOS
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
        enabled: true
        mode: '0644'

    - name: Configuring AppStream Repo
      ansible.builtin.yum_repository:
        file: ex294_repo
        name: EX294_STREM
        description: EX294 appstream software
        baseurl: http://10.10.1.200/alma10/AppStream
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
        enabled: true
        mode: '0644'

